.TH "PC.Combat.EnemyAnimationController" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Combat.EnemyAnimationController \- Controls how the enemy animations react to information in the environment\&.   

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDie\fP ()"
.br
.RI "Plays the enemy death animation when the animator has recorded the enemy as dead\&. The animator gets this information from the enemy controller\&.  "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
