.TH "PC.Combat.TouchSensor" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Combat.TouchSensor \- Records any contact between the player and the enemy\&. This allows the enemy to apply damage to the player on contact\&.   

.SH SYNOPSIS
.br
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
