.TH "PC.Combat.CharacterCombat" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Combat.CharacterCombat \- Defined the combat behavior specific to the player character\&.   

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAttack\fP (\fBCharacterStats\fP targetStats)"
.br
.RI "Attack the target\&. This is called when the player's gun gets a hit on a damageable object\&.  "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void PC\&.Combat\&.CharacterCombat\&.Attack (\fBCharacterStats\fP targetStats)"

.PP
\fBParameters\fP
.RS 4
\fItargetStats\fP The stats object for the target being hit\&. This controls the amount of damage it recieves\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
