.TH "PC.Combat" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Combat
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCharacterCombat\fP"
.br
.RI "Defined the combat behavior specific to the player character\&.  "
.ti -1c
.RI "class \fBEnemyAnimationController\fP"
.br
.RI "Controls how the enemy animations react to information in the environment\&.  "
.ti -1c
.RI "class \fBEnemyCombat\fP"
.br
.RI "Defines the combat behavior specific to our enemies\&.  "
.ti -1c
.RI "class \fBPlayerCombat\fP"
.br
.RI "Defines the combat behavior specific to our player\&.  "
.ti -1c
.RI "class \fBTouchSensor\fP"
.br
.RI "Records any contact between the player and the enemy\&. This allows the enemy to apply damage to the player on contact\&.  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
