.TH "PC.Entities.PlayerManager" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Entities.PlayerManager \- Creates a global instance of the player for easy reference by other scripts\&. Handles interface between player health and \fBUI\fP\&.   

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBplayer\fP = null"
.br
.RI "The global instance of the player\&.  "
.ti -1c
.RI "GameObject \fBhealthCount\fP = null"
.br
.RI "The player's current health\&.  "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPlayerManager\fP \fBinstance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
