.TH "PC.Entities.GunSO" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Entities.GunSO \- This class defines various parameters that control the gun's functionality and behavior\&. For instance, the gun's damage, range, and fire rate default values are defined here\&.   

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBRange\fP = 100f"
.br
.RI "The range within the gun can deal damage\&.  "
.ti -1c
.RI "float \fBDamage\fP = 20f"
.br
.RI "The damage the gun deals to the target\&.  "
.ti -1c
.RI "int \fBMagazineSize\fP = 30"
.br
.RI "The number of rounds in the gun's magazine\&.  "
.ti -1c
.RI "float \fBFireRate\fP = 10f"
.br
.RI "Max fire rate of the gun\&.  "
.ti -1c
.RI "float \fBReloadTime\fP = 3\&.0f"
.br
.RI "Time to reload\&.  "
.ti -1c
.RI "float \fBVerticalRecoil\fP = 2f"
.br
.RI "Vertical recoil component magnitude\&.  "
.ti -1c
.RI "float \fBHorizontalRecoil\fP = 0\&.5f"
.br
.RI "Horizontal recoil component magnitude\&.  "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
