.TH "PC.Entities.EnemyController" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Entities.EnemyController \- \fBEnemyController\fP is a class that handles the enemy's AI\&.
.br
The enemy is programmed with a navmeshagent to follow and attack the player when the player is in a specific range\&.   

.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBFaceTarget\fP ()"
.br
.RI "FaceTarget is a method that rotates the enemy towards the player during a chase\&.  "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
