.TH "PC.Input.InputModule" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Input.InputModule
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBProcess\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBInputModule\fP \fBinstance\fP\fC [get]\fP"
.br
.ti -1c
.RI "static InputActions \fBInputActions\fP\fC [get]\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static InputActions \fBh_inputActions\fP"
.br
.ti -1c
.RI "static bool \fB_awakeCalledFlag\fP = false"
.br
.ti -1c
.RI "static \fBInputModule\fP \fB_instance\fP = null"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
