.TH "PC.Stats" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Stats
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCharacterStats\fP"
.br
.RI "This class is used to store general stats and damage behavior common to all game characters\&.  "
.ti -1c
.RI "class \fBEnemyStats\fP"
.br
.RI "This class is used to store the enemy's stats and log its death\&.  "
.ti -1c
.RI "class \fBPlayerStats\fP"
.br
.RI "This class is used to store the player's stats and log its death to the console\&.  "
.ti -1c
.RI "class \fBStat\fP"
.br
.RI "Base class for all stats used to track character parameters\&.  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
