.TH "PC.Stats.Stat" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Stats.Stat \- Base class for all stats used to track character parameters\&.   

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetValue\fP ()"
.br
.RI "Getter for the stat value\&.  "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fB_baseValue\fP = 0"
.br
.RI "The base value of the stat\&.  "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int PC\&.Stats\&.Stat\&.GetValue ()"

.PP
\fBReturns\fP
.RS 4
integer stat value 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
