.TH "PC.Stats.EnemyStats" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.Stats.EnemyStats \- This class is used to store the enemy's stats and log its death\&.   

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDie\fP ()"
.br
.RI "Logs the enemy's death and can specify other death behavior not related to animations which are handled in the animation controller\&.  "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void PC\&.Stats\&.EnemyStats\&.Die ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPC\&.Stats\&.CharacterStats\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
