.TH "PC.UI.AlphaPMS" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.UI.AlphaPMS
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MarketModule \fBMarketModule\fP = null"
.br
.ti -1c
.RI "StashModule \fBStashModule\fP = new StashModule()"
.br
.ti -1c
.RI "TransportationModule \fBTransportationModule\fP = null"
.br
.ti -1c
.RI "MemoryModule \fBMemoryModule\fP = null"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
