.TH "PC.UI.PMSBase" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.UI.PMSBase
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QuestsModule \fBQuestsModule\fP = null"
.br
.ti -1c
.RI "CraftingModule \fBCraftingModule\fP = null"
.br
.ti -1c
.RI "SuitModule \fBSuitModule\fP = null"
.br
.ti -1c
.RI "WeaponUpgradingModule \fBWeaponUpgradingModule\fP = null"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
