.TH "PC.UI.LayoutMaintainPreferredHeight" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.UI.LayoutMaintainPreferredHeight
.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "RectTransform \fB_rectTransform\fP"
.br
.ti -1c
.RI "HorizontalOrVerticalLayoutGroup \fB_layoutGroup\fP"
.br
.ti -1c
.RI "float \fB_preferredHeight\fP = 0f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
