.TH "PC.UI.MenusController" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.UI.MenusController
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBPauseMenu\fP \fBPauseMenu\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBInventoryMenu\fP \fBInventoryMenu\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBDevConsoleMenu\fP \fBDevConsoleMenu\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBMapMenu\fP \fBMapMenu\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBPMSMenu\fP \fBPMSMenu\fP\fC [get]\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPauseMenu\fP \fB_pauseMenu\fP = null"
.br
.ti -1c
.RI "\fBInventoryMenu\fP \fB_inventoryMenu\fP = null"
.br
.ti -1c
.RI "\fBDevConsoleMenu\fP \fB_devConsoleMenu\fP = null"
.br
.ti -1c
.RI "\fBMapMenu\fP \fB_mapMenu\fP = null"
.br
.ti -1c
.RI "\fBPMSMenu\fP \fB_pmsMenu\fP = null"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBMenusController\fP \fB_instance\fP = null"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
