.TH "PC.UI.ItemTypes" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.UI.ItemTypes
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBbelongsTo\fP (\fBItemType\fP item)"
.br
.RI "Checks if a type belongs to a list of types\&.  "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "List< \fBItemType\fP > \fBtypes\fP = new List<\fBItemType\fP>()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool PC\&.UI\&.ItemTypes\&.belongsTo (\fBItemType\fP item)"

.PP
\fBParameters\fP
.RS 4
\fIitem\fP The type to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the type belongs to the list of types, else false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
