.TH "PC.UI.ScrollRectNoMouseDrag" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.UI.ScrollRectNoMouseDrag
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnBeginDrag\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnDrag\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "override void \fBOnEndDrag\fP (PointerEventData eventData)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
