.TH "PC.UI.Container" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.UI.Container
.SH SYNOPSIS
.br
.PP
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBStart\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBItem\fP \fB_itemPrefab\fP = null"
.br
.ti -1c
.RI "\fBItemSO\fP[] \fB_items\fP = null"
.br
.ti -1c
.RI "Vector2Int[] \fB_itemPositions\fP = null"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void PC\&.UI\&.Container\&.Start ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBPC\&.UI\&.ContainerBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
