.TH "PC.UI.ButtonAction" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.UI.ButtonAction
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBButtonAction\fP (string label, UnityEngine\&.Events\&.UnityAction action=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBLabel\fP"
.br
.ti -1c
.RI "UnityEngine\&.Events\&.UnityAction \fBAction\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
