.TH "PC.UI.PMSMenu" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.UI.PMSMenu
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (\fBBetaPMS\fP PMS)"
.br
.RI "Initializes the menu with the given betaPMS\&.  "
.ti -1c
.RI "void \fBInit\fP (\fBAlphaPMS\fP PMS)"
.br
.RI "Initializes the menu with the given alphaPMS\&.  "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwakeExtension\fP ()"
.br
.RI "DO NOT HIDE/OVERRIDE \fBMenuBase\&.Awake()\fP USING THE NEW OR OVERRIDE KEYWORDS!!! \fBAwakeExtension()\fP is called at the end of \fBMenuBase\&.Awake()\fP\&. If you need any code to run in MonoBehaviour\&.Awake() put it inside \fBAwakeExtension()\fP\&.  "
.ti -1c
.RI "override void \fBOpenExtension\fP ()"
.br
.RI "Gets called at the end of \fBOpen()\fP\&.  "
.ti -1c
.RI "override void \fBCloseExtension\fP ()"
.br
.RI "Gets called at the end of \fBClose()\fP\&.  "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "TMP_Text \fB_label\fP = null"
.br
.ti -1c
.RI "Button \fB_questsModuleButton\fP = null"
.br
.ti -1c
.RI "Button \fB_marketModuleButton\fP = null"
.br
.ti -1c
.RI "Button \fB_stashModuleButton\fP = null"
.br
.ti -1c
.RI "Button \fB_craftingModuleButton\fP = null"
.br
.ti -1c
.RI "Button \fB_suitModuleButton\fP = null"
.br
.ti -1c
.RI "Button \fB_weaponUpgradingModuleButton\fP = null"
.br
.ti -1c
.RI "Button \fB_transportationModuleButton\fP = null"
.br
.ti -1c
.RI "Button \fB_memoryModuleButton\fP = null"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void PC\&.UI\&.PMSMenu\&.AwakeExtension ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBPC\&.UI\&.MenuBase\fP\&.
.SS "override void PC\&.UI\&.PMSMenu\&.CloseExtension ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBPC\&.UI\&.MenuBase\fP\&.
.SS "void PC\&.UI\&.PMSMenu\&.Init (\fBAlphaPMS\fP PMS)"

.PP
\fBParameters\fP
.RS 4
\fIPMS\fP The alphaPMS to initialize the menu with\&.
.RE
.PP

.SS "void PC\&.UI\&.PMSMenu\&.Init (\fBBetaPMS\fP PMS)"

.PP
\fBParameters\fP
.RS 4
\fIPMS\fP The betaPMS to initialize the menu with\&.
.RE
.PP

.SS "override void PC\&.UI\&.PMSMenu\&.OpenExtension ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBPC\&.UI\&.MenuBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
