.TH "PC.VFX.WFX_LightFlicker" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.VFX.WFX_LightFlicker \- Controls the flickering of the light for the muzzle flash\&.   

.SH SYNOPSIS
.br
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "IEnumerator \fBFlicker\fP ()"
.br
.RI "Flickers the light component of this object\&. Object is meant to be a background light to muzzle flash  "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fB_flickerTime\fP = 0\&.05f"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "IEnumerator PC\&.VFX\&.WFX_LightFlicker\&.Flicker ()\fC [private]\fP"

.PP
\fBReturns\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
