.TH "PC.VFX" 3 "Fri Dec 9 2022" "Project Calamity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PC.VFX
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWFX_LightFlicker\fP"
.br
.RI "Controls the flickering of the light for the muzzle flash\&.  "
.in -1c
.SH "Detailed Description"
.PP 
Rapidly sets a light on/off\&.
.PP
(c) 2015, Jean Moreno 
.SH "Author"
.PP 
Generated automatically by Doxygen for Project Calamity from the source code\&.
